### ISSUE TITLE
OfficeDevPnP.Core v0.5.1030.7 dependency: Microsoft.IdentityModel

### ISSUE THREAD

**Issue by vcx** [OfficeDev/PnP#282]
In Windows 10 Technical Preview (build 9879) Microsoft.IdentityModel wasn't available on the system by default. It looks like the package OfficeDevPnP.Core v0.5.1030.7 needs it, but it wasn't marked as a dependency. WIF wasn't available to install in appwiz.cpl.

I did my tests with a "vanilla" Windows 10 TP + VS Ultimate update 4. After running Install-Package Microsoft.IdentityModel, the other command (install-package OfficeDevPnPCore16) worked correctly.

The full error log in Nuget Package Manager console is:

```
PM> install-package OfficeDevPnPCore16
Attempting to resolve dependency 'Microsoft.AspNet.WebApi.Client (≥ 5.2.2)'.
Attempting to resolve dependency 'Newtonsoft.Json (≥ 6.0.4)'.
Attempting to resolve dependency 'Microsoft.AspNet.WebApi.Core (≥ 5.2.2)'.
Attempting to resolve dependency 'AppForSharePointWebToolkit (≥ 3.0.1)'.
Installing 'Newtonsoft.Json 6.0.4'.
Successfully installed 'Newtonsoft.Json 6.0.4'.
Installing 'Microsoft.AspNet.WebApi.Client 5.2.2'.
You are downloading Microsoft.AspNet.WebApi.Client from Microsoft, the license agreement to which is available at http://www.microsoft.com/web/webpi/eula/net_library_eula_ENU.htm. Check the package for additional dependencies, which may come with their own license agreement(s). Your use of the package and dependencies constitutes your acceptance of their license agreements. If you do not accept the license agreement(s), then delete the relevant components from your device.
Successfully installed 'Microsoft.AspNet.WebApi.Client 5.2.2'.
Installing 'Microsoft.AspNet.WebApi.Core 5.2.2'.
You are downloading Microsoft.AspNet.WebApi.Core from Microsoft, the license agreement to which is available at http://www.microsoft.com/web/webpi/eula/net_library_eula_ENU.htm. Check the package for additional dependencies, which may come with their own license agreement(s). Your use of the package and dependencies constitutes your acceptance of their license agreements. If you do not accept the license agreement(s), then delete the relevant components from your device.
Successfully installed 'Microsoft.AspNet.WebApi.Core 5.2.2'.
Installing 'AppForSharePointWebToolkit 3.0.1'.
Successfully installed 'AppForSharePointWebToolkit 3.0.1'.
Installing 'OfficeDevPnPCore16 0.5.1030.7'.
You are downloading OfficeDevPnPCore16 from Office 365 Developer Patterns & Practices, the license agreement to which is available at https://github.com/OfficeDev/PnP/blob/master/LICENSE.md. Check the package for additional dependencies, which may come with their own license agreement(s). Your use of the package and dependencies constitutes your acceptance of their license agreements. If you do not accept the license agreement(s), then delete the relevant components from your device.
Successfully installed 'OfficeDevPnPCore16 0.5.1030.7'.
Adding 'Newtonsoft.Json 6.0.4' to ConsoleApplication5.
Successfully added 'Newtonsoft.Json 6.0.4' to ConsoleApplication5.
Adding 'Microsoft.AspNet.WebApi.Client 5.2.2' to ConsoleApplication5.
Successfully added 'Microsoft.AspNet.WebApi.Client 5.2.2' to ConsoleApplication5.
Adding 'Microsoft.AspNet.WebApi.Core 5.2.2' to ConsoleApplication5.
Successfully added 'Microsoft.AspNet.WebApi.Core 5.2.2' to ConsoleApplication5.
Adding 'AppForSharePointWebToolkit 3.0.1' to ConsoleApplication5.
Uninstalling 'AppForSharePointWebToolkit 3.0.1'.
Successfully uninstalled 'AppForSharePointWebToolkit 3.0.1'.
Uninstalling 'Microsoft.AspNet.WebApi.Core 5.2.2'.
Successfully uninstalled 'Microsoft.AspNet.WebApi.Core 5.2.2'.
Uninstalling 'Microsoft.AspNet.WebApi.Client 5.2.2'.
Successfully uninstalled 'Microsoft.AspNet.WebApi.Client 5.2.2'.
Uninstalling 'Newtonsoft.Json 6.0.4'.
Successfully uninstalled 'Newtonsoft.Json 6.0.4'.
Install failed. Rolling back...
install-package : Failed to add reference to 'Microsoft.IdentityModel'. Please make sure that it is in the Global Assembly Cache.
At line:1 char:1
+ install-package OfficeDevPnPCore16
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
```

[]s and congratulations for this great work,

Vinicius Xavier

**Comment by pbjorklund** [comment]
Has this been solved in the new build?

**Comment by jansenbe** [comment]
No idea...would need to be tested

**Comment by VesaJuvonen** [comment]
No issues with Win 10 due Nuget updates in the Core. Closing this one.

**Comment by asumner** [comment]
I've just downloaded the pnp partner package and I get Microsoft.Indenty 3.5 reference errors. I'm in visual studio 2015. I've installed the package but I still get reference errors. I'm on Windows 10 :)

**Comment by asumner** [comment]
I used the package manager to install Microsoft.Identity and the extensions also. All References fixed but I have 8 warnings about versions that could not be resolved. The build succeeds but I try to clear all warnings in my code.
